sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HCGLCr7FfRE4/W1k94PdJfUmS1rgrEIfekw4oX6DfFpDevjOlYs3Uzvwll76+KXJ4aQ8F0b4w/ThaOwwOuVOEMk2F4AHlPIKGPvYnHESVDc3CzCvsfpvR52UUhnKp7wgDp6dAhdiF3j8peyoRI/hLpqtfZdAAU0uCmehb08b6UxJ7bhk47bwi4coblE59IO6erZJfHJpKq7atzek1qaCxyU3i9vNF/GMF1MNcYW084+qo9pG4IHcJavy6V/EMzdMSOa53YfKvXzmwW0+hj51VRBkf8CcwVaFqNnEh6aVUHYx+m+DgPYz6G2Ox/n7RieskHOmErFxIDKtJTjUyhQBnJ6vgXa26eMPScOGJgKBE2cQ2EYVkvCwaXBB5OFhafp9tzOQV01Qgkt2Za9Rh5HARpkMyLqIulky8r+M/A7ATfjWy8W/VVfZsN8ddj7jYSacnyoNeiYRvJ0tlF8yG9fNpUWBmDLvdNAXH6EdyDd+MvYLYZRG4+KYjAvRWPM9RQ0Yig7A5PRpEKJnnQnKsP9V2tqhWxXYz8SxYGD91FpZxhWGFE0JKVhWQeLAc/jOlwsOJs4IgMQ+6NSgPq7Y0/b+V9uiwT5OrN4NvxvMX2n8a0KJZVYw7kL2zQEjG942LyoQNkec2V9xEvu6J+6L/TdEeoLHEiWgEyjyH6VW9MGSclI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Rover-Boys-out-West--Or-The-Search-for-a-Lost-Mine_6071
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy